Repository googleapis/java-securitycenter, pull requests merged in 2020-12, with the labels that each got.

#320 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full

#305 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#326 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#325 docs: Wrap samples with future prefix
  samples/snippets/src/main/java/com/google/cloud/examples/securitycenter/snippets/CreateNotificationConfigSnippets.java
  samples/snippets/src/main/java/com/google/cloud/examples/securitycenter/snippets/DeleteNotificationConfigSnippets.java
  samples/snippets/src/main/java/com/google/cloud/examples/securitycenter/snippets/GetNotificationConfigSnippets.java
  samples/snippets/src/main/java/com/google/cloud/examples/securitycenter/snippets/ListNotificationConfigSnippets.java
  samples/snippets/src/main/java/com/google/cloud/examples/securitycenter/snippets/NotificationReceiver.java
  samples/snippets/src/main/java/com/google/cloud/examples/securitycenter/snippets/UpdateNotificationConfigSnippets.java
Labels: api: securitycenter, automerge, cla: yes, samples

#339 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full

#338 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#342 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: securitycenter, cla: yes, context: full
