Repository googleapis/java-securitycenter, pull requests merged in 2020-06, with the labels that each got.

#149 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#152 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#154 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#156 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#166 feat: promote to GA
  .repo-metadata.json
  README.md
Labels: cla: yes

#168 chore: updated proto information for other languages
  proto-google-cloud-securitycenter-v1p1beta1/src/main/java/com/google/cloud/securitycenter/v1p1beta1/ResourceProto.java
  proto-google-cloud-securitycenter-v1p1beta1/src/main/proto/google/cloud/securitycenter/v1p1beta1/resource.proto
  synth.metadata
Labels: automerge, cla: yes, context: full

#174 docs: specify allowed fields for UpdateNotificationConfig
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1/SecurityCenterClient.java
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1p1beta1/SecurityCenterClient.java
  grpc-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/SecurityCenterGrpc.java
  grpc-google-cloud-securitycenter-v1p1beta1/src/main/java/com/google/cloud/securitycenter/v1p1beta1/SecurityCenterGrpc.java
  proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/securitycenter_service.proto
  proto-google-cloud-securitycenter-v1p1beta1/src/main/proto/google/cloud/securitycenter/v1p1beta1/securitycenter_service.proto
  synth.metadata
Labels: automerge, cla: yes, context: full

#175 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#180 chore: update README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#181 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-securitycenter/pom.xml
  grpc-google-cloud-securitycenter-v1/pom.xml
  grpc-google-cloud-securitycenter-v1beta1/pom.xml
  grpc-google-cloud-securitycenter-v1p1beta1/pom.xml
  pom.xml
  proto-google-cloud-securitycenter-v1/pom.xml
  proto-google-cloud-securitycenter-v1beta1/pom.xml
  proto-google-cloud-securitycenter-v1p1beta1/pom.xml
Labels: cla: yes

#192 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
