Repository googleapis/java-securitycenter, pull requests merged in 2021-02, with the labels that each got.

#365 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: securitycenter, cla: yes, context: partial

#367 chore: Re-generated to pick up changes from synthtool
  .github/workflows/auto-release.yaml
  LICENSE
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full

#368 fix: update repo name
  .kokoro/release/publish_javadoc11.cfg
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full

#374 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#371 docs: generate sample code in the Java microgenerator
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1/SecurityCenterClient.java
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1/package-info.java
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1beta1/SecurityCenterClient.java
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1beta1/package-info.java
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1p1beta1/SecurityCenterClient.java
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1p1beta1/package-info.java
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full, samples

#377 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full

#376 chore: update gapic-generator-java to 0.0.20
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1/stub/GrpcSecurityCenterStub.java
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1beta1/stub/GrpcSecurityCenterStub.java
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1p1beta1/stub/GrpcSecurityCenterStub.java
  google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1/MockSecurityCenterImpl.java
  google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1beta1/MockSecurityCenterImpl.java
  google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1p1beta1/MockSecurityCenterImpl.java
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full

#378 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full

#379 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full

#381 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full

#383 chore: release gapic-generator-java v0.0.21 with gapic_metadata.json support
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1/gapic_metadata.json
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1beta1/gapic_metadata.json
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1p1beta1/gapic_metadata.json
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full

#355 fix: deprecate files in v1beta1 that will be removed in next release
  proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/AssetSecurityMarksName.java
  proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/FindingSecurityMarksName.java
  proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/SecuritymarksName.java
Labels: api: securitycenter, cla: yes

#385 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#391 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#392 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#394 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#404 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes
