Repository googleapis/java-securitycenter, pull requests merged in 2021-07, with the labels that each got.

#553 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#546 chore: release gapic-generator-java v1.0.13
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1beta1/SecurityCenterClient.java
  google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1beta1/SecurityCenterClientTest.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/AssetName.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/FindingName.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/FolderName.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/NotificationConfigName.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/OrganizationName.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/OrganizationSettingsName.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/ProjectName.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/SecurityMarksName.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/SourceName.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/TopicName.java
  proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/AssetName.java
  proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/FindingName.java
  proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/OrganizationName.java
  proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/OrganizationSettingsName.java
  proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/SecurityMarksName.java
  proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/SourceName.java
  proto-google-cloud-securitycenter-v1p1beta1/src/main/java/com/google/cloud/securitycenter/v1p1beta1/AssetName.java
  proto-google-cloud-securitycenter-v1p1beta1/src/main/java/com/google/cloud/securitycenter/v1p1beta1/FindingName.java
  proto-google-cloud-securitycenter-v1p1beta1/src/main/java/com/google/cloud/securitycenter/v1p1beta1/FolderName.java
  proto-google-cloud-securitycenter-v1p1beta1/src/main/java/com/google/cloud/securitycenter/v1p1beta1/NotificationConfigName.java
  proto-google-cloud-securitycenter-v1p1beta1/src/main/java/com/google/cloud/securitycenter/v1p1beta1/OrganizationName.java
  proto-google-cloud-securitycenter-v1p1beta1/src/main/java/com/google/cloud/securitycenter/v1p1beta1/OrganizationSettingsName.java
  proto-google-cloud-securitycenter-v1p1beta1/src/main/java/com/google/cloud/securitycenter/v1p1beta1/ProjectName.java
  proto-google-cloud-securitycenter-v1p1beta1/src/main/java/com/google/cloud/securitycenter/v1p1beta1/SecurityMarksName.java
  proto-google-cloud-securitycenter-v1p1beta1/src/main/java/com/google/cloud/securitycenter/v1p1beta1/SourceName.java
  proto-google-cloud-securitycenter-v1p1beta1/src/main/java/com/google/cloud/securitycenter/v1p1beta1/TopicName.java
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: partial

#547 chore: minimize noise from build scripts
  .kokoro/coerce_logs.sh
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1/SecurityCenterClient.java
  google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1/SecurityCenterClientTest.java
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: partial

#556 fix: Add shopt -s nullglob to dependencies script
  .kokoro/dependencies.sh
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1/SecurityCenterClient.java
  google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1/SecurityCenterClientTest.java
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: partial

#555 chore: release gapic-generator-java v1.0.16
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1p1beta1/SecurityCenterClient.java
  google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1p1beta1/SecurityCenterClientTest.java
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: partial

#561 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#563 chore: remove distributionManagement section
  pom.xml
Labels: api: securitycenter, automerge, cla: yes

#564 chore: remove distributionManagement section
  google-cloud-securitycenter-bom/pom.xml
Labels: api: securitycenter, automerge, cla: yes

#567 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#566 chore: remove All rights reserved clause from java.header
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1/SecurityCenterClient.java
  google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1/SecurityCenterClientTest.java
  java.header
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: partial

#568 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#569 chore: add dependencyDashboardLabels to renovate.json
  renovate.json
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full

#573 chore: fix migration to owlbot
  .github/readme/synth.metadata/synth.metadata
  synth.py
Labels: api: securitycenter, automerge, cla: yes

#576 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: securitycenter, automerge, cla: yes

#584 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: securitycenter, automerge, cla: yes

#585 feat: configure initial sp version
  .github/workflows/ci.yaml
Labels: api: securitycenter, automerge, cla: yes
