Repository googleapis/java-securitycenter, pull requests merged in 2021-06, with the labels that each got.

#518 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#525 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#521 chore: release gapic-generator-java v1.0.10
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1/SecurityCenterClient.java
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1beta1/SecurityCenterClient.java
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1p1beta1/SecurityCenterClient.java
  google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1/SecurityCenterClientTest.java
  google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1beta1/SecurityCenterClientTest.java
  google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1p1beta1/SecurityCenterClientTest.java
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full

#528 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#407 docs: remove unused region tags
  samples/snippets/src/main/java/com/google/cloud/examples/securitycenter/snippets/CreateNotificationConfigSnippets.java
  samples/snippets/src/main/java/com/google/cloud/examples/securitycenter/snippets/DeleteNotificationConfigSnippets.java
  samples/snippets/src/main/java/com/google/cloud/examples/securitycenter/snippets/GetNotificationConfigSnippets.java
  samples/snippets/src/main/java/com/google/cloud/examples/securitycenter/snippets/ListNotificationConfigSnippets.java
  samples/snippets/src/main/java/com/google/cloud/examples/securitycenter/snippets/NotificationReceiver.java
  samples/snippets/src/main/java/com/google/cloud/examples/securitycenter/snippets/UpdateNotificationConfigSnippets.java
Labels: api: securitycenter, cla: yes

#537 docs: update currently supported Finding filter fields
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1/SecurityCenterClient.java
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1p1beta1/SecurityCenterClient.java
  google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1/SecurityCenterClientTest.java
  google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1beta1/SecurityCenterClientTest.java
  google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1p1beta1/SecurityCenterClientTest.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/CreateFindingRequest.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/CreateFindingRequestOrBuilder.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/CreateNotificationConfigRequest.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/CreateNotificationConfigRequestOrBuilder.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/CreateSourceRequest.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/CreateSourceRequestOrBuilder.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GetOrganizationSettingsRequest.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GetOrganizationSettingsRequestOrBuilder.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GroupAssetsRequest.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GroupAssetsRequestOrBuilder.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GroupFindingsRequest.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/GroupFindingsRequestOrBuilder.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/ListFindingsRequest.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/ListFindingsRequestOrBuilder.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/ListSourcesRequest.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/ListSourcesRequestOrBuilder.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/RunAssetDiscoveryRequest.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/RunAssetDiscoveryRequestOrBuilder.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/UpdateFindingRequest.java
  proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/UpdateFindingRequestOrBuilder.java
  proto-google-cloud-securitycenter-v1/src/main/proto/google/cloud/securitycenter/v1/securitycenter_service.proto
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full

#534 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#538 chore: release gapic-generator-java v1.0.12
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1/SecurityCenterClient.java
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1/stub/SecurityCenterStubSettings.java
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1beta1/stub/SecurityCenterStubSettings.java
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1p1beta1/stub/SecurityCenterStubSettings.java
  google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1/SecurityCenterClientTest.java
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: partial

#541 fix: Update dependencies.sh to not break on mac
  .kokoro/dependencies.sh
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1/SecurityCenterClient.java
  google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1/SecurityCenterClientTest.java
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: partial

#542 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#550 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes
