Repository googleapis/java-securitycenter, pull requests merged in 2021-05, with the labels that each got.

#476 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: none

#478 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: securitycenter, automerge, cla: yes

#479 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full

#488 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#490 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#491 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full

#497 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#500 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#501 chore: release gapic-generator-java v1.0.5
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1/SecurityCenterClient.java
  google-cloud-securitycenter/src/main/java/com/google/cloud/securitycenter/v1p1beta1/SecurityCenterClient.java
  google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1/SecurityCenterClientTest.java
  google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1p1beta1/SecurityCenterClientTest.java
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full

#509 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#510 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#502 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full

#512 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: securitycenter, automerge, cla: yes

#513 feat: add gcf-owl-bot[bot] to ignoreAuthors
  .github/generated-files-bot.yml
  .kokoro/build.sh
  synth.metadata
Labels: api: securitycenter, cla: yes, context: full
